#
# Copyright Altoros. All Rights Reserved.
#

version: '2'

volumes:
  orderer.DOMAIN:

services:

  orderer.DOMAIN:
    container_name: orderer.DOMAIN
    image: hyperledger/fabric-orderer:FABRIC_VERSION
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /etc/hyperledger
    command: orderer
    ports:
      - ORDERER_PORT:7050
    volumes:
        - ../artifacts/channel:/etc/hyperledger/configtx
        - ../artifacts/crypto-config/ordererOrganizations/DOMAIN/orderers/orderer.DOMAIN/:/etc/hyperledger/crypto/orderer
        - orderer.DOMAIN:/var/hyperledger/production/orderer
#        - ../artifacts/crypto-config/peerOrganizations/ORG1.DOMAIN/peers/peer0.ORG1.DOMAIN/:/etc/hyperledger/crypto/peerORG1
#        - ../artifacts/crypto-config/peerOrganizations/ORG2.DOMAIN/peers/peer0.ORG2.DOMAIN/:/etc/hyperledger/crypto/peerORG2
#        - ../artifacts/crypto-config/peerOrganizations/ORG3.DOMAIN/peers/peer0.ORG3.DOMAIN/:/etc/hyperledger/crypto/peerORG3

  cli.DOMAIN:
    container_name: cli.DOMAIN
    extends:
      file: base-intercept.yaml
      service: cli-base
#    volumes:
#       - ../artifacts/hosts/MAIN_ORG/cli_hosts:/etc/hosts
#      - ../artifacts/crypto-config/ordererOrganizations/DOMAIN/orderers/orderer.DOMAIN/tls:/etc/hyperledger/crypto/orderer/tls
    CLI_EXTRA_HOSTS

  # simple http server to disseminate certificates
  www.DOMAIN:
    extends:
      file: base-intercept.yaml
      service: www-base
    container_name: www.DOMAIN
    ports:
      - WWW_PORT:80
      
  zookeeper0:
    container_name: zookeeper0
    extends:
      file: base-intercept.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2889:3889 server.3=zookeeper2:2890:3890
    ports:
      - 2181
      - 2888
      - 3888

  zookeeper1:
    container_name: zookeeper1
    extends:
      file: base-intercept.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2889:3889 server.3=zookeeper2:2890:3890
    ports:
      - 2182
      - 2889
      - 3889

  zookeeper2:
    container_name: zookeeper2
    extends:
      file: base-intercept.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2889:3889 server.3=zookeeper2:2890:3890
    ports:
      - 2183
      - 2890
      - 3890

  kafka0:
    container_name: kafka0
    extends:
      file: base-intercept.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2182,zookeeper2:2183
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
        - 9092:9092

  kafka1:
    container_name: kafka1
    extends:
      file: base-intercept.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2182,zookeeper2:2183
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 9093:9092

  kafka2:
    container_name: kafka2
    extends:
      file: base-intercept.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2182,zookeeper2:2183
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 9094:9092

  kafka3:
    container_name: kafka3
    extends:
      file: base-intercept.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2182,zookeeper2:2183
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 9095:9092

